# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punkty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herbata',
            old_name='product',
            new_name='type',
        ),
    ]
